const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const out = path.join(root, 'android/app/src/main/assets');
fs.mkdirSync(out, { recursive: true });
let html = fs.readFileSync(path.join(root, 'public/index.html'), 'utf8');
html = html.replace('</head>', '<link rel="stylesheet" href="/android.css"><script src="/android.js"></script></head>');
fs.writeFileSync(path.join(out, 'index.html'), html);
let js = fs.readFileSync(path.join(root, 'public/app.js'), 'utf8');
const signature = 'async function api(path, options = {}) {';
if (!js.includes(signature)) throw new Error('The web API adapter changed; update the Android bridge.');
js = js.replace(signature, signature + '\n  return window.androidRequest(path, options);\n/* Desktop transport is intentionally unreachable in the Android build. */');
js = js.replace('async function refreshStatus() {', 'async function refreshStatus() {\n  if (state.busy) return;');
js = js.replace('  refreshStatus();\n  setInterval', '  refreshStatus();\n  api("/api/restore").then(refreshStatus).catch(() => {});\n  setInterval');
fs.writeFileSync(path.join(out, 'app.js'), js);
fs.copyFileSync(path.join(root, 'public/styles.css'), path.join(out, 'styles.css'));
for (const name of ['android.js', 'android.css']) fs.copyFileSync(path.join(root, 'android/web', name), path.join(out, name));
const { COMMANDS } = require('../server');
const { KEY_CODES } = require('../netcast');
fs.writeFileSync(path.join(out, 'commands.json'), JSON.stringify({ webos: COMMANDS, netcast: KEY_CODES }));
console.log('Prepared offline Android UI and TV command mappings.');
